------------------1.CREATE TABLE DIM DATE--------------------
CREATE TABLE IF NOT EXISTS dim_date (
    date_key INT PRIMARY KEY,
    full_date TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    day SMALLINT NOT NULL,
    month SMALLINT NOT NULL,
    year SMALLINT NOT NULL,
    quarter SMALLINT NOT NULL,
    week_of_year SMALLINT NOT NULL,
    day_of_week SMALLINT NOT NULL,
    day_name VARCHAR(9) NOT NULL,
    is_weekend BOOLEAN NOT NULL DEFAULT FALSE,
    is_holiday BOOLEAN NOT NULL DEFAULT FALSE,
    holiday_name VARCHAR(50)
)DISTSTYLE ALL;

------------------2.CREATE TABLE DIM TERRITORY--------------------
CREATE TABLE IF NOT EXISTS dim_territory(
    territory_key INT PRIMARY KEY,
    territory_id VARCHAR,
    market VARCHAR(20) NOT NULL,
    region VARCHAR(30) NOT NULL,
    country VARCHAR(30) NOT NULL,
    state VARCHAR(50) NOT NULL,
    city VARCHAR(30) NOT NULL,
    row_is_current BOOLEAN DEFAULT TRUE NOT NULL,
    row_start_date TIMESTAMP WITHOUT TIME ZONE DEFAULT GETDATE() NOT NULL,
    row_end_date TIMESTAMP WITHOUT TIME ZONE DEFAULT NULL,
    row_change_reason VARCHAR(200) DEFAULT NULL
)DISTSTYLE KEY DISTKEY(territory_id);


-------------------3.CREATE DIM PRODUCT ------------------------------
CREATE TABLE dim_product (
    product_key INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id INT NOT NULL,
    product_name VARCHAR(50) NOT NULL,
    category_name VARCHAR(50),
    row_is_current BOOLEAN DEFAULT TRUE NOT NULL,
    row_start_date TIMESTAMP WITHOUT TIME ZONE DEFAULT GETDATE() NOT NULL,
    row_end_date TIMESTAMP WITHOUT TIME ZONE DEFAULT NULL,
    row_change_reason VARCHAR(200) DEFAULT NULL
) DISTSTYLE ALL;

-------------------5.CREATE DIM CUSTOMER -------------------------------
CREATE TABLE Dim_Customer (
    customer_key INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer_id INT NOT NULL,
    customer_name VARCHAR(30),
    customer_country VARCHAR(20),
    customer_state VARCHAR(3),
    customer_city VARCHAR(30),
    customer_street VARCHAR(50),
    row_is_current BOOLEAN DEFAULT TRUE NOT NULL,
    row_start_date TIMESTAMP WITHOUT TIME ZONE DEFAULT GETDATE() NOT NULL,
    row_end_date TIMESTAMP WITHOUT TIME ZONE DEFAULT NULL,
    row_change_reason VARCHAR(200) DEFAULT NULL
) DISTSTYLE ALL;

  
